@startsalt
{+
    <u><b>Backlog期限切れチケット抽出ツール</b></u>
    ..
    ◆設定◆ 
    {
        対象PJID： | "99999"
        接続方法： | {
                [X]API Key | → | {API Key： | "xxxxxxxxxxxxxxxxx " }
                [ ] ID/PW | → | {ID： | "xxxxxx " | PW： | "***** " }
            }
    }
    ..
    { [検索 <&magnifying-glass>] | [終了 <&account-logout>] }
    {
        - エラメッセージ１
        - エラメッセージ２
    }
    ..
    ◆検索結果◆
    合計：99件
    {#
        チケット番号 | タイトル | 期限 | 担当者 | 作成者
        PJ-NAME_0001 | 【インフラ】テスト環境構築 | 2020/04/05 | 太郎 | 花子
        PJ-NAME_0001 | 【インフラ】テスト環境構築 | 2020/04/05 | 太郎 | 花子
        PJ-NAME_0001 | 【インフラ】テスト環境構築 | 2020/04/05 | 太郎 | 花子
        PJ-NAME_0001 | 【インフラ】テスト環境構築 | 2020/04/05 | 太郎 | 花子
        PJ-NAME_0001 | 【インフラ】テスト環境構築 | 2020/04/05 | 太郎 | 花子
        PJ-NAME_0001 | 【インフラ】テスト環境構築 | 2020/04/05 | 太郎 | 花子
        PJ-NAME_0001 | 【インフラ】テスト環境構築 | 2020/04/05 | 太郎 | 花子
    }    
}
@endsalt